<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.projectunified</groupId>
        <artifactId>uni-dialog</artifactId>
        <version>1.6.0-SNAPSHOT</version>
    </parent>

    <artifactId>uni-dialog-viaversion-spigot</artifactId>
    <name>UniDialog ViaVersion Spigot</name>

    <repositories>
        <repository>
            <id>viaversion</id>
            <url>https://repo.viaversion.com</url>
        </repository>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.github.projectunified</groupId>
            <artifactId>uni-dialog-viaversion</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.21.6-R0.1-20250630.141818-13</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.viaversion</groupId>
            <artifactId>viaversion-api</artifactId>
            <version>5.11.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.viaversion</groupId>
            <artifactId>viaversion-common</artifactId>
            <version>5.11.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.viaversion</groupId>
            <artifactId>nbt</artifactId>
            <version>5.3.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>17.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.10.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.10.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
            </plugin>
        </plugins>
    </build>
</project>
